// Command grapelogo turns the Concord grape logo (ConcordLogo.png) into the
// data internal/client renders as a live-shaded ASCII logo.
//
// A Go port of data/logo.py from the concord-site project
// (github.com/Anthoneyq/concord-site): the eight grapes are spheres fitted to
// the logo that the client shades per character like donut.c, so the light
// can move; the leaf and stem are traced from the image as fixed characters.
//
//	go run ./tools/grapelogo                  # regenerate internal/client/grape_logo_data.go
//	go run ./tools/grapelogo -cols 50 -json   # print the site's logo.json shape, to diff against it
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"image"
	"image/png"
	"log"
	"math"
	"os"
	"strings"
)

const ramp = ".,-~:;=!*#$@"

// x, y, radius, depth in logo pixels (1024 px image); depth decides which
// grape sits in front.
var grapes = [][4]float64{
	{430, 448, 70, 20}, {562, 475, 76, 40}, {364, 538, 68, 0}, {660, 527, 67, 0},
	{462, 584, 74, 45}, {602, 613, 65, 20}, {410, 670, 60, 0}, {518, 721, 70, 50},
}

// Sizes baked into the client: 35 columns is 21 rows, the height of the
// login screen's logo slot.
var clientSizes = []int{35}

type logoData struct {
	Cols   int          `json:"cols"`
	Rows   int          `json:"rows"`
	CW     float64      `json:"cw"`
	CH     float64      `json:"ch"`
	Grapes [][4]float64 `json:"grapes"`
	Chars  []string     `json:"chars"`
	Tones  []string     `json:"tones"`
}

func main() {
	src := flag.String("src", "ConcordLogo.png", "logo image")
	cols := flag.Int("cols", 0, "generate a single size")
	asJSON := flag.Bool("json", false, "print JSON (with -cols) instead of writing Go")
	out := flag.String("out", "internal/client/grape_logo_data.go", "Go output file")
	flag.Parse()

	f, err := os.Open(*src)
	if err != nil {
		log.Fatal(err)
	}
	img, err := png.Decode(f)
	f.Close()
	if err != nil {
		log.Fatal(err)
	}

	if *asJSON {
		b, _ := json.Marshal(generate(img, *cols))
		fmt.Println(string(b))
		return
	}
	sizes := clientSizes
	if *cols > 0 {
		sizes = []int{*cols}
	}
	var gen strings.Builder
	gen.WriteString("// Code generated by tools/grapelogo from ConcordLogo.png - DO NOT EDIT.\n\npackage client\n\nvar grapeLogos = map[int]grapeLogoData{\n")
	for _, c := range sizes {
		d := generate(img, c)
		fmt.Fprintf(&gen, "\t%d: {\n\t\tcols: %d, rows: %d, cw: %v, ch: %v,\n\t\tgrapes: [][4]float64{\n", c, d.Cols, d.Rows, d.CW, d.CH)
		for _, g := range d.Grapes {
			fmt.Fprintf(&gen, "\t\t\t{%v, %v, %v, %v},\n", g[0], g[1], g[2], g[3])
		}
		gen.WriteString("\t\t},\n\t\tchars: []string{\n")
		for _, s := range d.Chars {
			fmt.Fprintf(&gen, "\t\t\t%q,\n", s)
		}
		gen.WriteString("\t\t},\n\t\ttones: []string{\n")
		for _, s := range d.Tones {
			fmt.Fprintf(&gen, "\t\t\t%q,\n", s)
		}
		gen.WriteString("\t\t},\n\t},\n")
	}
	gen.WriteString("}\n")
	if err := os.WriteFile(*out, []byte(gen.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Println("wrote", *out)
}

// pyRound matches Python 3's round(): half to even.
func pyRound(x float64, places int) float64 {
	p := math.Pow(10, float64(places))
	return math.RoundToEven(x*p) / p
}

func generate(img image.Image, cols int) logoData {
	b := img.Bounds()
	W, H := b.Dx(), b.Dy()
	rgba := func(x, y int) (r, g, bl, a float64) {
		cr, cg, cb, ca := img.At(b.Min.X+x, b.Min.Y+y).RGBA()
		if ca == 0 {
			return 0, 0, 0, 0
		}
		// Un-premultiply back to 8-bit straight alpha, as PIL's RGBA gives.
		a8 := float64(ca >> 8)
		return math.Round(float64(cr) * 255 / float64(ca)), math.Round(float64(cg) * 255 / float64(ca)), math.Round(float64(cb) * 255 / float64(ca)), a8
	}

	// Bounding box of pixels with alpha > 128 (x1, y1 exclusive), like
	// PIL's getchannel('A').point(...).getbbox().
	x0, y0, x1, y1 := W, H, 0, 0
	for y := 0; y < H; y++ {
		for x := 0; x < W; x++ {
			if _, _, _, a := rgba(x, y); a > 128 {
				x0, y0 = min(x0, x), min(y0, y)
				x1, y1 = max(x1, x+1), max(y1, y+1)
			}
		}
	}
	cw := float64(x1-x0) / float64(cols)
	ch := cw * 2 // a character is 0.6em x 1.2em
	rows := int(pyRound(float64(y1-y0)/ch, 0))

	inGrape := func(x, y float64) bool {
		for _, g := range grapes {
			if (x-g[0])*(x-g[0])+(y-g[1])*(y-g[1]) < g[2]*g[2] {
				return true
			}
		}
		return false
	}

	d := logoData{Cols: cols, Rows: rows, CW: pyRound(cw, 3), CH: pyRound(ch, 3)}
	for row := 0; row < rows; row++ {
		var cs, ts strings.Builder
		for col := 0; col < cols; col++ {
			n, leaf, stem := 0, 0, 0
			lsum := 0.0
			for j := 0; j < 8; j++ {
				for i := 0; i < 4; i++ {
					x := int(float64(x0) + (float64(col)+(float64(i)+.5)/4)*cw)
					y := int(float64(y0) + (float64(row)+(float64(j)+.5)/8)*ch)
					n++
					if x >= W || y >= H || inGrape(float64(x), float64(y)) {
						continue
					}
					r, g, bl, a := rgba(x, y)
					if a < 128 {
						continue
					}
					hue, l := rgbToHL(r/255, g/255, bl/255)
					deg := hue * 360
					switch {
					case deg >= 60 && deg <= 180:
						leaf++
					case deg <= 50 || deg >= 330:
						stem++
					default:
						continue
					}
					lsum += l
				}
			}
			k := leaf + stem
			if float64(k)/float64(n) < .2 {
				cs.WriteByte(' ')
				ts.WriteByte(' ')
				continue
			}
			l := lsum / float64(k)
			ink := math.Min(1, math.Max(0, (l-.22)/.42)) * math.Min(1, float64(k)/float64(n)*1.4)
			idx := int(pyRound(ink*float64(len(ramp)-1), 0))
			cs.WriteByte(ramp[max(0, min(len(ramp)-1, idx))])
			threshold := .46
			if leaf >= stem {
				threshold = .44
			}
			light := l > threshold
			switch {
			case leaf >= stem && light:
				ts.WriteByte('G')
			case leaf >= stem:
				ts.WriteByte('g')
			case light:
				ts.WriteByte('O')
			default:
				ts.WriteByte('o')
			}
		}
		d.Chars = append(d.Chars, cs.String())
		d.Tones = append(d.Tones, ts.String())
	}
	for _, g := range grapes {
		d.Grapes = append(d.Grapes, [4]float64{pyRound(g[0]-float64(x0), 1), pyRound(g[1]-float64(y0), 1), g[2], g[3]})
	}
	return d
}

// rgbToHL is Python's colorsys.rgb_to_hls, returning hue and lightness.
func rgbToHL(r, g, b float64) (h, l float64) {
	maxc, minc := math.Max(r, math.Max(g, b)), math.Min(r, math.Min(g, b))
	l = (minc + maxc) / 2
	if minc == maxc {
		return 0, l
	}
	rc, gc, bc := (maxc-r)/(maxc-minc), (maxc-g)/(maxc-minc), (maxc-b)/(maxc-minc)
	switch {
	case r == maxc:
		h = bc - gc
	case g == maxc:
		h = 2 + rc - bc
	default:
		h = 4 + gc - rc
	}
	h = math.Mod(h/6, 1)
	if h < 0 {
		h++
	}
	return h, l
}
