package client

import (
	"math/rand"
	"time"
)

// Banner represents an ASCII art banner
type Banner struct {
	Name   string // Font name
	Art    string
	Height int
}

// banners is defined in banners_generated.go (generated by tools/extract_banners.go)

var rng = rand.New(rand.NewSource(time.Now().UnixNano()))

// GetRandomBanner returns a random ASCII art banner
func GetRandomBanner() Banner {
	return banners[rng.Intn(len(banners))]
}

// GetBannerByIndex returns a specific banner (for testing)
func GetBannerByIndex(index int) Banner {
	if index < 0 || index >= len(banners) {
		return banners[0]
	}
	return banners[index]
}
