// Package grapes draws Concord's shaded ASCII grape logo for programs other
// than the client, which has its own copy with all its styles
// (internal/client/grape_logo.go). The installer greets people with it.
//
// The eight grapes are spheres shaded per character like donut.c, so a
// light can move across them; the leaf and stem are fixed characters traced
// from the logo image. logo_data.go is generated by
//
//	go run ./tools/grapelogo -pkg grapes -out internal/grapes/logo_data.go
package grapes

import (
	"math"
	"strings"

	"github.com/charmbracelet/lipgloss"
)

type grapeLogoData struct {
	cols, rows int
	cw, ch     float64
	grapes     [][4]float64 // x, y, radius, depth in logo pixels
	chars      []string
	tones      []string
}

// Size is the logo's width in columns; it is Rows tall.
const (
	Size = 35
	Rows = 21
	ramp = ".,-~:;=!*#$@"
)

// The resting light, and the dark side it powers on from.
var (
	Light = Norm([3]float64{-.42, -.52, .8})
	Dark  = Norm([3]float64{.5, .6, -.7})
)

// Cell is one character of a frame and its tone: p0–p3 for the grapes
// (dark to highlight), g1/g2 the leaf, o1/o2 the stem, "" for blank.
type Cell struct {
	Ch   byte
	Tone string
}

type cell struct {
	grape         bool
	x, y, z       float64 // surface normal
	occ, coverage float64
	ch            byte
	tone          string
}

var cache []cell

// Norm scales v to unit length.
func Norm(v [3]float64) [3]float64 {
	m := math.Sqrt(v[0]*v[0] + v[1]*v[1] + v[2]*v[2])
	if m == 0 {
		m = 1
	}
	return [3]float64{v[0] / m, v[1] / m, v[2] / m}
}

// Ease moves the light a step from cur toward to, the way the client's
// light glides (0.17 of the way each 30 fps frame).
func Ease(cur, to [3]float64) [3]float64 {
	for i := range cur {
		cur[i] += (to[i] - cur[i]) * .1719
	}
	return Norm(cur)
}

// Orbit is the idle light's position t radians round its slow orbit.
func Orbit(t float64) [3]float64 {
	return Norm([3]float64{Light[0] + .32*math.Cos(t), Light[1] + .22*math.Sin(t), Light[2]})
}

// cells samples each character cell 3×5 times against the spheres
// (nearest surface wins; a grape in front casts a contact shadow on the
// one behind) and averages the hits into one normal per cell.
func cells() []cell {
	if cache != nil {
		return cache
	}
	L := grapeLogos[Size]
	const sx, sy = 3, 5
	toneOf := map[byte]string{'G': "g2", 'g': "g1", 'O': "o2", 'o': "o1"}
	type hit struct{ n, x, y, z, o float64 }
	out := make([]cell, 0, L.rows*L.cols)
	for r := 0; r < L.rows; r++ {
		for c := 0; c < L.cols; c++ {
			hits := make([]hit, len(L.grapes))
			for j := 0; j < sy; j++ {
				for i := 0; i < sx; i++ {
					x := (float64(c) + (float64(i)+.5)/sx) * L.cw
					y := (float64(r) + (float64(j)+.5)/sy) * L.ch
					best, bz := -1, math.Inf(-1)
					var n [3]float64
					for k, g := range L.grapes {
						dx, dy := (x-g[0])/g[2], (y-g[1])/g[2]
						if d := dx*dx + dy*dy; d < 1 {
							nz := math.Sqrt(1 - d)
							if z := g[3] + g[2]*nz; z > bz {
								bz, best, n = z, k, [3]float64{dx, dy, nz}
							}
						}
					}
					if best < 0 {
						continue
					}
					occ := 0.0
					for k, g := range L.grapes {
						if k == best || g[3] <= L.grapes[best][3] {
							continue
						}
						if d := math.Hypot(x-g[0], y-g[1]) / g[2]; d < 1.25 {
							occ = math.Max(occ, 1-(d-1)/.25)
						}
					}
					h := &hits[best]
					h.n++
					h.x += n[0]
					h.y += n[1]
					h.z += n[2]
					h.o += occ
				}
			}
			best, total := -1, 0.0
			for k := range hits {
				total += hits[k].n
				if hits[k].n > 0 && (best < 0 || hits[k].n > hits[best].n) {
					best = k
				}
			}
			coverage := total / (sx * sy)
			if best >= 0 && coverage >= .3 {
				h := hits[best]
				m := math.Sqrt(h.x*h.x + h.y*h.y + h.z*h.z)
				out = append(out, cell{grape: true, x: h.x / m, y: h.y / m, z: h.z / m, occ: h.o / h.n, coverage: coverage})
				continue
			}
			out = append(out, cell{ch: L.chars[r][c], tone: toneOf[L.tones[r][c]]})
		}
	}
	cache = out
	return out
}

// Frame shades the logo for light L.
func Frame(L [3]float64) [][]Cell {
	cs := cells()
	hv := Norm([3]float64{L[0], L[1], L[2] + 1})
	out := make([][]Cell, Rows)
	for r := range out {
		out[r] = make([]Cell, Size)
		for c := range out[r] {
			cl := cs[r*Size+c]
			if !cl.grape {
				out[r][c] = Cell{Ch: cl.ch, Tone: cl.tone}
				if cl.ch == ' ' {
					out[r][c].Tone = ""
				}
				continue
			}
			d := math.Max(0, cl.x*L[0]+cl.y*L[1]+cl.z*L[2])
			sp := math.Pow(math.Max(0, cl.x*hv[0]+cl.y*hv[1]+cl.z*hv[2]), 28)
			rim := math.Min(1, math.Max(0, (cl.z-.14)/.4))
			lum := math.Min(1, (.34+.66*d)*rim*(1-.9*cl.occ)*math.Min(1, cl.coverage*1.3)+.9*sp)
			tone := "p0"
			switch {
			case sp > .5:
				tone = "p3"
			case lum > .6:
				tone = "p2"
			case lum > .3:
				tone = "p1"
			}
			out[r][c] = Cell{Ch: ramp[int(math.Floor(lum*float64(len(ramp)-1)+.5))], Tone: tone}
		}
	}
	return out
}

// Render draws a frame with a style per tone (missing tones print plain).
func Render(frame [][]Cell, styles map[string]lipgloss.Style) string {
	var b strings.Builder
	for i, row := range frame {
		if i > 0 {
			b.WriteByte('\n')
		}
		for j := 0; j < len(row); {
			k := j
			var run strings.Builder
			for k < len(row) && row[k].Tone == row[j].Tone {
				run.WriteByte(row[k].Ch)
				k++
			}
			if st, ok := styles[row[j].Tone]; ok {
				b.WriteString(st.Render(run.String()))
			} else {
				b.WriteString(run.String())
			}
			j = k
		}
	}
	return b.String()
}
